# Generated by Django 5.0.7 on 2024-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_compartilhamentoprogresso_registroemocao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('intensidade', models.IntegerField()),
            ],
        ),
    ]
