# Generated by Django 5.0.7 on 2024-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_personalizacao_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacao',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
