# Generated by Django 5.0.7 on 2024-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisePadroesEmocionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_relatorio', models.CharField(max_length=100, verbose_name='ID do relatório')),
                ('id_usuario', models.CharField(max_length=100, verbose_name='ID do usuário')),
                ('data_inicio', models.DateField(verbose_name='Data de início da análise')),
                ('data_fim', models.DateField(verbose_name='Data de término da análise')),
                ('resumo_emocional', models.TextField(verbose_name='Resumo emocional')),
            ],
            options={
                'verbose_name': 'Análise de Padrões Emocionais',
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoProgressso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartilhar_progresso', models.CharField(max_length=100, verbose_name='compartilhar progreso: adicionar link')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Progresso',
            },
        ),
        migrations.CreateModel(
            name='IntegracaoDiarioPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anotacao', models.CharField(max_length=100, verbose_name='ID da anotação')),
                ('id_usuario', models.CharField(max_length=100, verbose_name='ID do usuário')),
                ('data_hora', models.DateTimeField(verbose_name='Data e horário da integração no diário')),
                ('texto_anotacao', models.TextField(verbose_name='Anotação no diário')),
            ],
            options={
                'verbose_name': 'Integração com o Diário pessoal',
                'verbose_name_plural': 'Integrações com o Diário pessoal',
            },
        ),
        migrations.CreateModel(
            name='Personalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=100, verbose_name='ID do usuário')),
                ('nome_usuario', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.CharField(max_length=100, verbose_name='Idade')),
                ('sexo', models.CharField(max_length=100, verbose_name='sexo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmocão',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=100, verbose_name='ID do usuário')),
                ('data_hora', models.DateTimeField(verbose_name='Data e horário do registro')),
                ('tipo_de_emocao', models.CharField(max_length=100, verbose_name='Tipo de emoção')),
                ('intensidade', models.CharField(max_length=100, verbose_name='Intensidade da emoção')),
            ],
            options={
                'verbose_name': 'Registro diário de Emoção',
                'verbose_name_plural': 'Registro diário de emoções',
            },
        ),
        migrations.CreateModel(
            name='SugestaoAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atividade', models.CharField(max_length=100, verbose_name='id da atividade')),
                ('nome_atividade', models.CharField(max_length=100, verbose_name='nome da atividade')),
                ('descricao', models.CharField(max_length=100, verbose_name='descrição')),
                ('beneficios_emocionais', models.CharField(max_length=100, verbose_name='beneficios emocionais das atividades')),
            ],
            options={
                'verbose_name': 'sugestção de atividade',
                'verbose_name_plural': 'sugestões de atividades',
            },
        ),
    ]
