# Generated by Django 5.0.7 on 2024-07-24 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizacao',
            options={'verbose_name': 'Personalização'},
        ),
        migrations.AddField(
            model_name='registroemocão',
            name='analise_padroes_emocionais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.analisepadroesemocionais', verbose_name='Análise de Padrões Emocionais'),
        ),
    ]
