# Generated by Django 5.0.7 on 2024-10-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_emocao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sugestaoatividades',
            options={'verbose_name': 'Sugestão de atividade', 'verbose_name_plural': 'Sugestões de atividades'},
        ),
        migrations.RemoveField(
            model_name='compartilhamentoprogresso',
            name='data',
        ),
        migrations.RemoveField(
            model_name='compartilhamentoprogresso',
            name='progresso',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='nome_usuario',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='registroemocao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='compartilhamentoprogresso',
            name='link',
            field=models.CharField(default='seu_valor_padrao_aqui', max_length=255),
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='Nome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='id_personalizacao',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroemocao',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroemocao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroemocao',
            name='emocao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registroemocao',
            name='intensidade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sugestaoatividades',
            name='beneficios_emocionais',
            field=models.CharField(max_length=100, verbose_name='benefícios emocionais das atividades'),
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='Senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
